language: generic
os: osx
osx_image: xcode10.2
jdk:
  # Buck requires Java 8
  - oraclejdk8 
addons:
  homebrew:
    brewfile: true
before_install:
  - bundle install
  - buck --version
  - java -version
env:
  - TERM=dumb
script: 
  - make ci
