language: generic
os: osx
osx_image: xcode10.1
jdk:
  - oraclejdk11
addons:
  homebrew:
    brewfile: true
before_install:
  - bundle install
  - buck --version
  - java -version
env:
  - TERM=dumb
script: 
  - make ci
